# Generated by Django 5.2.8 on 2026-01-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday')], max_length=3)),
                ('reservation_code', models.CharField(max_length=4, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('men', models.PositiveIntegerField()),
                ('women', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
