# Generated by Django 5.2.8 on 2026-01-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reserv_alter_phone_id_alter_phone_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='day',
            field=models.CharField(max_length=3),
        ),
    ]
