# Generated by Django 6.0 on 2026-01-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_days_alter_phone_id_alter_reserv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="days",
            name="status",
            field=models.CharField(default="able", max_length=10),
        ),
    ]
