# Generated by Django 6.0 on 2026-01-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_days_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserv",
            name="children",
        ),
    ]
