# Generated by Django 6.0 on 2026-01-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_reserv_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserv",
            name="day",
            field=models.CharField(max_length=15),
        ),
    ]
