# Generated by Django 6.0 on 2026-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_reserv_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="days",
            name="day",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="reserv",
            name="day",
            field=models.CharField(max_length=20),
        ),
    ]
