# Generated by Django 6.0 on 2026-01-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_days_day_alter_reserv_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="days",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
